version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: sessionmgr-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  sessionmgr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sessionmgr-app
    ports:
      - "8080:8080"
      - "9090:9090"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_PORT=8080
    volumes:
      - ./configs:/app/configs
    restart: unless-stopped

volumes:
  redis_data: 